#!/usr/bin/env bash

./stop || true
./build docker || exit 1

echo "### Starting lobby-introspect service docker ###"

lobby_introspect_service_port=${LOBBY_INTROSPECT_SERVICE_PORT:-8080}
docker run --rm --name lobby-introspect-service -d -p ${lobby_introspect_service_port}:8080 \
    -e JAVA_MAX_HEAP_SIZE=2G \
    -e LOBBY_SERVICE_URL=${LOBBY_SERVICE_URL} \
    -e INSTANCE=dev \
    docker-metascrum.artifacts.dbccloud.dk/lobby-introspect-service:devel
attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${lobby_introspect_service_port}/api/status); do
    if [[ ${attempts} -eq ${max_attempts} ]]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for lobby-introspect service ###"
curl -vs http://localhost:${lobby_introspect_service_port}/api/status
echo ""
